version: '3.8'

services:
  prepmate:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/prepmate
      - JWT_SECRET=your-production-jwt-secret
      - GEMINI_API_KEY=your-gemini-api-key
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:

